import type { Metadata } from "next";
import { Instrument_Sans, Inter } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",  
  weight: ["400", "500", "600", "700"], 
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",  
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`
          ${instrumentSans.variable} 
          ${inter.variable} 
          font-instrument 
          font-medium 
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
  
}
